//! Emit point-cloud values for `parity/parity_open3d.py` to recompute with Open3D.
//!
//! Prints only; asserts nothing. The comparison lives on the Python side so that
//! Open3D stays an independent reference rather than something this file agrees
//! with by construction.
//!
//! Run: `cargo run -q -p cv-3d --example parity_open3d`
//!
//! Every cloud below is generated by a closed-form formula (an integer lattice,
//! a lattice plus three far outliers, or a unit sphere by spherical coordinates),
//! so both sides generate byte-identical inputs without shipping a file. The
//! Python side restates the formulas independently rather than copying them from
//! a shared definition.

use cv_3d::filters::{
    estimate_normals_knn, radius_outlier_removal, statistical_outlier_removal, voxel_downsample,
};
use cv_3d::spatial::{KDTree, VoxelGrid};
use nalgebra::{Point3, Vector3};

/// A 3x3x3 lattice at spacing `sp`, centred on the origin: the `cluster` helper
/// the workspace's own `filters` tests use, so the reference has a documented
/// case to match.
fn cluster(n: usize, sp: f64) -> Vec<Point3<f64>> {
    let mut pts = Vec::with_capacity(n * n * n);
    let size = (n as f64 - 1.0) * sp;
    for i in 0..n {
        for j in 0..n {
            for k in 0..n {
                pts.push(Point3::new(
                    i as f64 * sp - size / 2.0,
                    j as f64 * sp - size / 2.0,
                    k as f64 * sp - size / 2.0,
                ));
            }
        }
    }
    pts
}

/// The same lattice plus three points at 100 units on each axis.
///
/// Three far outliers rather than one: a single outlier perturbs the global mean
/// and standard deviation of the statistical filter enough to move the threshold
/// for *every* point, so the comparison could not tell "the filter found the
/// outlier" from "the threshold moved and everything else survived by luck".
fn cluster_plus_outliers(sp: f64) -> Vec<Point3<f64>> {
    let mut pts = cluster(3, sp);
    pts.push(Point3::new(100.0, 0.0, 0.0));
    pts.push(Point3::new(0.0, 100.0, 0.0));
    pts.push(Point3::new(0.0, 0.0, 100.0));
    pts
}

/// A unit sphere sampled in spherical coordinates, poles included.
///
/// The analytic normal at `p` on the unit sphere is `p` itself, so every normal
/// has an exact closed-form answer to be compared against and no estimate of
/// anyone's behaviour is needed. Poles included because a pole's neighbours are
/// all at one latitude: excluding them would hide a sign or tie-break defect.
fn sphere(radius: f64, n_theta: usize, n_phi: usize) -> (Vec<Point3<f64>>, Vec<Vector3<f64>>) {
    let mut pts = Vec::new();
    let mut nrm = Vec::new();
    for i in 0..=n_theta {
        let th = std::f64::consts::PI * i as f64 / n_theta as f64;
        let st = th.sin();
        let ct = th.cos();
        for j in 0..n_phi {
            let ph = 2.0 * std::f64::consts::PI * j as f64 / n_phi as f64;
            let p = Point3::new(radius * st * ph.cos(), radius * st * ph.sin(), radius * ct);
            // Analytic outward normal of a sphere is the radial direction.
            let n = p.coords / radius;
            pts.push(p);
            nrm.push(n);
        }
    }
    (pts, nrm)
}

/// `VoxelGrid::downsample` (the `f32` spatial path) on the same cloud, so the two
/// Rust voxel implementations in this workspace are compared against Open3D
/// separately and the divergence can be located.
fn emit_voxel_grid(pts: &[Point3<f64>], vs: f64, name: &str) {
    // The grid is keyed relative to `origin`; the origin here is the cloud's own
    // minimum corner, which is what makes the origin-dependent keying visible.
    let pts_f32: Vec<Point3<f32>> = pts
        .iter()
        .map(|p| Point3::new(p.x as f32, p.y as f32, p.z as f32))
        .collect();
    let mut min = Point3::new(f32::MAX, f32::MAX, f32::MAX);
    for p in &pts_f32 {
        min = Point3::new(min.x.min(p.x), min.y.min(p.y), min.z.min(p.z));
    }
    let mut grid = VoxelGrid::new(min, vs as f32);
    for (i, p) in pts_f32.iter().enumerate() {
        grid.insert(*p, i);
    }
    let out = grid.downsample(&pts_f32);
    println!("#VGCOUNT {name} {}", out.len());
    for p in &out {
        println!("#VGP {name} {:.17e} {:.17e} {:.17e}", p.x, p.y, p.z);
    }
}

fn main() {
    // ---------------------------------------------------------------- voxels
    // Case `neg`: points on both sides of the origin, so a floor-of-absolute vs
    // trunc-toward-zero keying rule disagree.
    println!("#CASE voxel_neg");
    {
        let pts = vec![
            Point3::new(-1.0, 0.0, 0.0),
            Point3::new(-0.9, 0.0, 0.0),
            Point3::new(-0.1, 0.0, 0.0),
            Point3::new(0.0, 0.0, 0.0),
            Point3::new(0.9, 0.0, 0.0),
            Point3::new(1.2, 0.0, 0.0),
        ];
        for &vs in &[0.5f64, 0.3] {
            let r = voxel_downsample(&pts, None, None, vs);
            println!("#VDN {vs} {}", r.points.len());
            for p in &r.points {
                println!("#VDP {vs} {:.17e} {:.17e} {:.17e}", p.x, p.y, p.z);
            }
        }
    }

    // Case `grid`: the 3x3x3 lattice at spacing 0.1 downsampled by 0.3, where
    // 0.1/0.3 is not integral and several points share a voxel.
    println!("#CASE voxel_grid");
    {
        let pts = cluster(3, 0.1);
        for &vs in &[0.3f64, 0.15] {
            let r = voxel_downsample(&pts, None, None, vs);
            println!("#VDN {vs} {}", r.points.len());
            for p in &r.points {
                println!("#VDP {vs} {:.17e} {:.17e} {:.17e}", p.x, p.y, p.z);
            }
        }
        emit_voxel_grid(&pts, 0.3, "grid03");
        emit_voxel_grid(&pts, 0.15, "grid015");
    }

    // --------------------------------------------------------------- outliers
    // Index-set comparison, as the task requires: the retained *indices* are
    // printed, not the filtered coordinates.
    println!("#CASE outlier_sor");
    {
        let pts = cluster_plus_outliers(0.1);
        for &(nb, sr) in &[(5usize, 2.0f64), (5, 1.0), (8, 2.0), (20, 2.0), (4, 2.0)] {
            let (_, idx) = statistical_outlier_removal(&pts, nb, sr);
            println!("#SOR {nb} {sr} {}", idx.len());
            for &i in &idx {
                println!("#SOI {nb} {sr} {i}");
            }
        }
    }

    println!("#CASE outlier_ror");
    {
        let pts = cluster_plus_outliers(0.1);
        for &(r, mn) in &[(0.5f64, 2usize), (0.2, 2), (0.15, 3), (0.5, 1), (0.12, 4)] {
            let (_, idx) = radius_outlier_removal(&pts, r, mn);
            println!("#ROR {r} {mn} {}", idx.len());
            for &i in &idx {
                println!("#ROI {r} {mn} {i}");
            }
        }
    }

    // ----------------------------------------------------------------- normals
    // Compared up to sign: a normal direction is a line, not an arrow.
    println!("#CASE normals_sphere");
    {
        let (pts, analytic) = sphere(1.0, 12, 24);
        for &k in &[20usize, 8] {
            let est = estimate_normals_knn(&pts, k);
            println!("#NRM {k} {}", est.len());
            for n in &est {
                println!("#NV {k} {:.17e} {:.17e} {:.17e}", n.x, n.y, n.z);
            }
        }
        // The analytic normals, so the Python side can check the Rust input is
        // the intended cloud rather than trusting the estimate.
        println!("#NANALYTIC {}", analytic.len());
        for n in &analytic {
            println!("#NA {:.17e} {:.17e} {:.17e}", n.x, n.y, n.z);
        }
    }

    // A plane at z = 0.25: the analytic normal is exactly (0,0,1) and every
    // estimate is degenerate-free, so a covariance or sign error has nowhere to
    // hide. Compare against Open3D's non-fast path, which is the covariance
    // method, so this is a like-for-like method comparison.
    println!("#CASE normals_plane");
    {
        let pts: Vec<Point3<f64>> = (0..5)
            .flat_map(|i| (0..5).map(move |j| Point3::new(i as f64 * 0.1, j as f64 * 0.1, 0.25)))
            .collect();
        let est = estimate_normals_knn(&pts, 8);
        println!("#NRM 8 {}", est.len());
        for n in &est {
            println!("#NV 8 {:.17e} {:.17e} {:.17e}", n.x, n.y, n.z);
        }
    }

    // ------------------------------------------------------------------ kNN
    // Open3D's `compute_knn_graph` vs this workspace's `KDTree`. The kNN *set*
    // is the well-defined object; the ordering within it is not, because
    // Open3D's nanoflann-based search and this tree both leave ties at equal
    // distance unresolved and leave it unresolved differently. The harness
    // therefore compares the sets and reports the ordering separately.
    println!("#CASE knn");
    {
        let pts = cluster(3, 0.1);
        let pts_f32: Vec<Point3<f32>> = pts
            .iter()
            .map(|p| Point3::new(p.x as f32, p.y as f32, p.z as f32))
            .collect();
        let mut items: Vec<(Point3<f32>, usize)> = pts_f32
            .iter()
            .copied()
            .enumerate()
            .map(|(i, p)| (p, i))
            .collect();
        let tree = KDTree::build(&mut items);

        for &k in &[6usize, 4] {
            println!("#KNN {k}");
            for (i, q) in pts_f32.iter().enumerate() {
                let res = tree.k_nearest_neighbors(q, k);
                let got: Vec<usize> = res.iter().map(|(_, i, _)| *i).collect();
                println!("#KQ {k} {i} {}", got.len());
                for &j in &got {
                    println!("#KI {k} {i} {j}");
                }
            }
        }
    }

    // ------------------------------------------------------------------ ICP
    // Point-to-plane ICP against Open3D's `registration_icp`.
    //
    // A bumpy height field `p(u,v) = (u, v, h(u,v))` with **analytic** normals
    // `(-dh/du, -dh/dv, 1)`, and a source displaced by a known rigid motion.
    //
    // An earlier draft used the unit cube this workspace's own ICP tests use. It
    // is the wrong surface for this comparison, and measuring why is part of the
    // result: a cube's six faces carry only six distinct normals, so the 6x6
    // point-to-plane system is rank-deficient and the linear solve is not
    // unique. Reproducing the Rust algorithm in numpy on that cube returns
    // `numpy.linalg.LinAlgError: Singular matrix`, while Open3D silently falls
    // back to a pseudo-inverse. Two correct-looking answers to a degenerate
    // question is the situation this workspace keeps finding, so the surface
    // here has varying normals and a well-conditioned system.
    println!("#CASE icp");
    {
        use cv_3d::gpu::registration::icp_point_to_plane;
        use cv_3d::PointCloud;
        use nalgebra::{Matrix3, Matrix4};

        // h(u,v) = A sin(2 pi u) + B cos(2 pi v); non-zero in both derivatives
        // at every sample, so no face is flat and no normal is degenerate.
        const A: f64 = 0.20;
        const B: f64 = 0.15;
        const NU: usize = 25;
        const NV: usize = 25;
        let mut pts = Vec::with_capacity(NU * NV);
        let mut nrm = Vec::with_capacity(NU * NV);
        for i in 0..NU {
            for j in 0..NV {
                let u = i as f64 / (NU - 1) as f64;
                let v = j as f64 / (NV - 1) as f64;
                let h = A * (2.0 * std::f64::consts::PI * u).sin()
                    + B * (2.0 * std::f64::consts::PI * v).cos();
                let dhdu = 2.0 * std::f64::consts::PI * A * (2.0 * std::f64::consts::PI * u).cos();
                let dhdv = -2.0 * std::f64::consts::PI * B * (2.0 * std::f64::consts::PI * v).sin();
                pts.push(Point3::new(u, v, h));
                // Analytic normal of the graph z = h(x, y).
                nrm.push(Vector3::new(-dhdu, -dhdv, 1.0).normalize());
            }
        }

        // Ground truth: rotate `ang` radians about z, then translate.
        let ang = 3.0f64.to_radians();
        let (c, s) = (ang.cos(), ang.sin());
        let gt = Matrix4::<f64>::new(
            c, -s, 0.0, 0.01, s, c, 0.0, -0.02, 0.0, 0.0, 1.0, 0.03, 0.0, 0.0, 0.0, 1.0,
        );

        let target = PointCloud {
            points: pts
                .iter()
                .map(|p| Point3::new(p.x as f32, p.y as f32, p.z as f32))
                .collect(),
            normals: Some(
                nrm.iter()
                    .map(|n| Vector3::new(n.x as f32, n.y as f32, n.z as f32))
                    .collect(),
            ),
            colors: None,
        };

        // The source is the target carried *backwards* by the ground truth, so
        // the correct transform ICP must return is exactly `gt`. There is a
        // known right answer here, not merely "the two resemble each other".
        let inv = gt.try_inverse().unwrap();
        let inv3 = Matrix3::<f64>::new(
            inv[(0, 0)],
            inv[(0, 1)],
            inv[(0, 2)],
            inv[(1, 0)],
            inv[(1, 1)],
            inv[(1, 2)],
            inv[(2, 0)],
            inv[(2, 1)],
            inv[(2, 2)],
        );
        let inv_t = Vector3::<f64>::new(inv[(0, 3)], inv[(1, 3)], inv[(2, 3)]);
        let r3 = Matrix3::new(c, -s, 0.0, s, c, 0.0, 0.0, 0.0, 1.0);
        let source = PointCloud {
            points: target
                .points
                .iter()
                .map(|p| {
                    let m = inv3 * Vector3::new(p.x as f64, p.y as f64, p.z as f64) + inv_t;
                    Point3::new(m.x as f32, m.y as f32, m.z as f32)
                })
                .collect(),
            normals: Some(
                nrm.iter()
                    .map(|n| {
                        let m = r3 * n;
                        Vector3::new(m.x as f32, m.y as f32, m.z as f32).normalize()
                    })
                    .collect(),
            ),
            colors: None,
        };

        println!("#ICPGT {c:.17e} {s:.17e} {ang:.17e}");
        println!("#ICPGTX {:.17e} {:.17e} {:.17e}", 0.01, -0.02, 0.03);
        println!("#ICPN {}", target.points.len());
        println!("#ICPMD 0.05");
        println!("#ICPNRM");
        for n in target.normals.as_ref().unwrap() {
            println!("#ICPNV {:.17e} {:.17e} {:.17e}", n.x, n.y, n.z);
        }
        println!("#ICPP");
        for p in &target.points {
            println!("#ICPPV {:.17e} {:.17e} {:.17e}", p.x, p.y, p.z);
        }

        // `cv_3d::gpu::registration::icp_point_to_plane` is the ICP reachable from
        // this crate without adding a dependency; `cv_registration` provides a
        // second, separately-implemented point-to-plane ICP but `cv-3d` does not
        // depend on it, and a Cargo.toml edit is out of scope for this harness.
        match icp_point_to_plane(
            &source.points,
            &target.points,
            target.normals.as_ref().unwrap(),
            0.05,
            100,
        ) {
            Ok(t) => {
                for (i, j, v) in [
                    (0usize, 0usize, t[(0, 0)]),
                    (0, 1, t[(0, 1)]),
                    (0, 3, t[(0, 3)]),
                    (1, 0, t[(1, 0)]),
                    (1, 1, t[(1, 1)]),
                    (1, 3, t[(1, 3)]),
                    (2, 3, t[(2, 3)]),
                ] {
                    println!("#ICPM {i} {j} {v:.17e}");
                }
            }
            Err(e) => println!("#ICPERR {e}"),
        }
    }
}
