[package]
name = "cv-scientific"
version = "0.1.0"
edition = "2021"

[dependencies]
cv-math = { workspace = true }
cv-geometry2d = { workspace = true }
cv-signal = { workspace = true }
cv-pointcloud = { workspace = true }

[dev-dependencies]
geo = { workspace = true }
cv-core = { workspace = true }
nalgebra = { workspace = true }

[features]
default = []
